image:
  resources:
    cpu: 500m
    memory: 300Mi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
